# Generated by Django 5.1.1 on 2024-10-16 03:35

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=300, verbose_name='Действие')),
                ('is_nice', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveIntegerField(choices=[(1, 'Every day'), (2, 'Every work day'), (3, 'Every weekend'), (4, 'Every week')], default=1, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=300, null=True, verbose_name='Вознаграждение')),
                ('duration', models.DurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=120))], verbose_name='Длительность выполнения (сек)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_habit', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('pk',),
            },
        ),
    ]
