# Generated by Django 5.1.1 on 2024-10-17 02:07

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.DurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=120))], verbose_name='Длит-сть выполнения (сек)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
